### ISSUE TITLE
ghcr.io/gaussmeter/teslamater package not linked to teslamater repo

### ISSUE THREAD

**Issue by tobiasehlert** [gaussmeter/teslamater#7]
Since the move to ghcr.io, the pull of image by using the init script (https://github.com/gaussmeter/gaussmeter/blob/master/init_containers.sh) doesn't work.

From what I can see, the package is not linked to the teslamater repository.

https://github.com/gaussmeter/gaussmeter/blob/2f39c07da0ac7962d72355c19857f29aa2795682/init_containers.sh#L4

**Comment by LelandSindt** [comment]
I looks like a permissions issue... I will review...

**Comment by LelandSindt** [comment]
`teslamater` was set to private, I have changed it to public you should be able to pull the image now. Thank you.
